### ISSUE TITLE
Input 2x: NO HP, KK, KTP (Tanpa spasi, Disable Copas) – Double confirm data field sama

### ISSUE THREAD

**Issue by msramdan** [msramdan/motor#22]
Penting saat input data customer: Input 2x: NO HP, KK, KTP (Tanpa spasi, Disable Copas) – Double confirm data field sama
Harus 2x input field bagian No HP, No KTP, No KK.
Sistem harus mengecek data kedua field nya sama. Harus disable copas juga. Data harus diketik.
Tujuannya kita mau pastikan bagian HP, KTP, dan KK adalah benar.
Karena ini adalah data kontak customer paling penting bagi perusahaan.

**Comment by rachyharkov** [comment]
#38
