### ISSUE TITLE
buat faktur pdf untuk data kendaraan/pembelian kendaraan

### ISSUE THREAD

**Issue by msramdan** [msramdan/motor#26]
buat faktur pdf untuk data kendaraan/pembelian kendaraan pada button read

**Comment by rachyharkov** [comment]
faktur kendaraaan?

![image](https://user-images.githubusercontent.com/44340813/124455301-9eeabb00-ddb3-11eb-91a3-409ff0b1097d.png)

**Comment by rachyharkov** [comment]
**_Halaman 11_**

Jenis detail informasi yang diperlukan utk item:
    • No BPKB –wajib isi
    • No Polisi- wajib isi
    • Kategori: Barang atau Leasing – wajib isi
    • Jenis: Motor atau mobil –wajib isi
    • Nama Barang (ini adalah nama pemilik barang yang tertulis di BPKB)- wajib isi
    • Tahunbuat - wajibisi
    • Merk (Honda, Yamaha, Kawasaki, Suzuki, Toyota, Mitshubisi, Daihatsu, dll)-wajib isi
    • Type (NMAX, Beat, Supra, Kijang, Ertiga, dll)-wajib isi
    • Warna 1-wajib isi: Merah,hitam,kuning, hijau,biru,putih,ungu,orange,coklat,abuabu,pink,emas,perak,birudongker,marun
    • Warna 2-opsional:Merah,hitam,kuning, hijau,biru,putih,ungu,orange,coklat,abuabu,pink,emas,perak,birudongker,marun
    • Kondisi (%): 0-100 - wajibisi
    • No Mesin: -wajibisi
    • No Rangka: -wajibisi
    • Harga pokok-bysistem- wajib isi
    • Harga Perolehan-default 0- wajib isi
    • Biaya rekondisi-default 0- wajib isi
    • Biaya STNK-default 0- wajib isi
    • Biaya admin-default 0- wajib isi
    • Biaya Komisi-default 0- wajib isi
    • Biaya Lainnya-default 0- wajib isi

[dokumentasi2.docx](https://github.com/msramdan/motor/files/6766705/dokumentasi2.docx)

**Comment by rachyharkov** [comment]
ok, berdasarkan diskusi terakhir, berarti terapkaan aja data2 yang tampil sesuai apa yg tampil di read

**Comment by rachyharkov** [comment]
#40
