### ISSUE TITLE
4 Jenis Otorisasi pada transaksi penjualan angsuran

### ISSUE THREAD

**Issue by msramdan** [msramdan/motor#32]
4 Jenis Otorisasi pada transaksi penjualan angsuran
Contoh penggunaan akan dijelaskan dibawah
Untuk transaksi penjualan yang jenis angsuran/cicilan, akan ada 4 jenis otorisasi yang diperlukan

Khusus otorisasi no 1 & 2, dilakukan diawal waktu user menginput transaksi baru, sebelum transaksi penjualan aktif.
Khusus otorisasi no 3 & 4, dilakukan ditengah jalan, saat penjualan sudah aktif (user ingin edit penjualan trsbt dan melakukan special action cth: lunas maju, & diskon denda).

**Comment by rachyharkov** [comment]
Jadi sebuah kesulitan besar kalau level user dan hak akses jadi dinamis

kayaknya ntar dibikin opsi **strict authorization** pada level user dan dibuat modul khusus untuk menampung otorisasi yang diinginkan TANPA MENGHILANGKAN fungsi dinamis hak akses dan level user, sehingga bisa diimplementasikan modul hak akses untuk project lain 

tentunya mengembalikan nilai status izin sesuai dengan otorisasi yang dipengenin, i'll try...
