### ISSUE TITLE
rubah semua angka jadi nama,, cek menu master dan menu karyawan bagian read dan report excel

### ISSUE THREAD

**Issue by msramdan** [msramdan/motor#35]
rubah semua angka jadi nama,, cek menu master dan menu karyawan bagian read dan report excel semua yang ber relasi rubah jadi nama

**Comment by rachyharkov** [comment]
#39 relasi ke unit, skarang yang awalnya tampil id unit jadi nama unit
![image](https://user-images.githubusercontent.com/44340813/124837797-c6a67280-dfaf-11eb-8862-b356b5394e99.png)
![image](https://user-images.githubusercontent.com/44340813/124837898-f48bb700-dfaf-11eb-9627-55b9fa04b3e0.png)
