### ISSUE TITLE
Laporan Pembelian DAN laporan kendaraan

### ISSUE THREAD

**Issue by msramdan** [msramdan/motor#7]
Membuat laporan pembelian atau laporan pada menu kendaraan di sesuaikan dengan data excel di google drive ,, looping list harga tambahan kendaraan masing2

**Comment by rachyharkov** [comment]
bang, gw butuh db terbaru dari lu @msramdan

**Comment by rachyharkov** [comment]
nvm, db udh ada, otw ngerjain
